# API Contract: RAG Backend Frontend Integration

## OpenAPI Specification

```yaml
openapi: 3.0.3
info:
  title: RAG Backend API
  description: API for RAG (Retrieval-Augmented Generation) backend integration with book frontend
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.yourdomain.com
    description: Production server

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns system health status and dependency availability
      responses:
        '200':
          description: Health status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '503':
          description: Service unavailable due to dependency issues
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /rag/query:
    post:
      summary: Query the RAG system with general book-wide questions
      description: Process a user query against the full book content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful query response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Bad request due to invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /rag/query-selected-text:
    post:
      summary: Query the RAG system with selected text constraints
      description: Process a user query restricted to user-selected text content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelectedTextQueryRequest'
      responses:
        '200':
          description: Successful query response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Bad request due to invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    QueryRequest:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the query (generated if not provided)
          example: "query_12345"
        question:
          type: string
          description: The user's question text
          example: "What are the fundamental principles discussed in the book?"
        session_id:
          type: string
          description: Session identifier for conversation tracking
          example: "session_abc123"
        metadata:
          type: object
          description: Additional metadata for the query
          additionalProperties: true
      required:
        - question

    SelectedTextQueryRequest:
      allOf:
        - $ref: '#/components/schemas/QueryRequest'
        - type: object
          properties:
            selected_text_only:
              type: boolean
              description: Whether to restrict search to selected text only
              default: false
              example: true
            selected_text_content:
              type: string
              description: The specific text content to search within when selected_text_only is true
              example: "The fundamental principles of robotics include kinematics, dynamics, control theory..."
          required:
            - selected_text_only
            - selected_text_content

    QueryResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the response
          example: "response_67890"
        answer:
          type: string
          description: The final answer generated by the RAG agent
          example: "The fundamental principles include kinematics, dynamics, and control theory..."
        citations:
          type: array
          description: List of sources used to generate the answer
          items:
            $ref: '#/components/schemas/Citation'
        retrieved_chunks:
          type: array
          description: Details of chunks used in the response
          items:
            $ref: '#/components/schemas/RetrievedChunk'
        refusal_reason:
          type: string
          description: Reason if the query was refused (e.g., "not found in book")
          example: "No relevant content found in the book for the given query."
        deterministic_hash:
          type: string
          description: Hash for verifying determinism
          example: "a1b2c3d4e5f6..."
        timestamp:
          type: number
          description: Unix timestamp of response generation
          format: float
          example: 1678886400.123456
        session_id:
          type: string
          description: Session identifier if provided in request
          example: "session_abc123"
      required:
        - id
        - answer
        - citations
        - retrieved_chunks
        - timestamp

    Citation:
      type: object
      properties:
        source_url:
          type: string
          description: URL of the source document
          example: "/docs/fundamentals/principles"
        module:
          type: string
          description: Module identifier from the book
          example: "Fundamentals"
        chapter:
          type: string
          description: Chapter identifier from the book
          example: "Introduction to Robotics"
        section:
          type: string
          description: Section identifier if available
          example: "Core Principles"
      required:
        - source_url
        - module
        - chapter

    RetrievedChunk:
      type: object
      properties:
        text:
          type: string
          description: The actual text content retrieved
          example: "The fundamental principles of robotics include kinematics, which studies motion..."
        score:
          type: number
          description: Similarity score (0.0 to 1.0)
          format: float
          minimum: 0.0
          maximum: 1.0
          example: 0.85
        source_url:
          type: string
          description: URL of the source document
          example: "/docs/fundamentals/principles"
        module:
          type: string
          description: Module identifier from the book
          example: "Fundamentals"
        chapter:
          type: string
          description: Chapter identifier from the book
          example: "Introduction to Robotics"
        chunk_index:
          type: integer
          description: Index of the chunk within the source
          example: 1
      required:
        - text
        - score
        - source_url
        - module
        - chapter
        - chunk_index

    HealthResponse:
      type: object
      properties:
        status:
          type: string
          description: Overall system status
          enum: [healthy, degraded, unhealthy]
          example: healthy
        timestamp:
          type: number
          description: Unix timestamp of check
          format: float
          example: 1678886400.123456
        dependencies:
          type: object
          description: Status of individual dependencies
          properties:
            qdrant:
              type: boolean
              description: Qdrant vector store availability
              example: true
            openai_api:
              type: boolean
              description: OpenAI API availability
              example: true
            cohere_api:
              type: boolean
              description: Cohere API availability
              example: true
          required:
            - qdrant
            - openai_api
            - cohere_api
        version:
          type: string
          description: API version
          example: "1.0.0"
      required:
        - status
        - timestamp
        - dependencies
        - version

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: "Invalid query: question must be a non-empty string"
        code:
          type: string
          description: Error code
          example: "INVALID_INPUT"
        details:
          type: object
          description: Additional error details
          additionalProperties: true
      required:
        - error
        - code
```

## Endpoint Details

### GET /health
- **Purpose**: Check system health and dependency availability
- **Authentication**: None required
- **Rate Limiting**: None
- **Response Time SLA**: <100ms
- **Cache Policy**: No caching

### POST /rag/query
- **Purpose**: Process general book-wide questions
- **Authentication**: None required (public API)
- **Rate Limiting**: Configurable based on deployment
- **Response Time SLA**: <5000ms (5 seconds)
- **Timeout**: 30 seconds
- **Content-Type**: application/json

### POST /rag/query-selected-text
- **Purpose**: Process questions constrained to user-selected text
- **Authentication**: None required (public API)
- **Rate Limiting**: Configurable based on deployment
- **Response Time SLA**: <5000ms (5 seconds)
- **Timeout**: 30 seconds
- **Content-Type**: application/json

## Error Handling

### HTTP Status Codes
- 200: Success
- 400: Bad Request (invalid input parameters)
- 401: Unauthorized (if authentication implemented)
- 429: Too Many Requests (rate limiting)
- 500: Internal Server Error
- 503: Service Unavailable (dependency unavailable)

### Error Response Format
All error responses follow the ErrorResponse schema with standardized error codes:
- `INVALID_INPUT`: Request parameters failed validation
- `DEPENDENCY_ERROR`: External service unavailable
- `PROCESSING_ERROR`: Internal processing error
- `QUOTA_EXCEEDED`: Rate limit or usage quota exceeded